name: Hellow World Test action for streaming

on: [push] #Trigger on every push

jobs:
  build:
  runs-on: ubuntu-latest  # Use Ubuntu runner

  steps:
  - uses: actions/checkout@v2 
  - name: Write a multi-line message
    run: echo This demo file shows a 
      echo very basic and easy-to-understand workflow.
    
